### ISSUE TITLE
Marker category filter

### ISSUE THREAD

**Issue by LukasBaecker** [LukasBaecker/FoodWaste#3]
user should be able to filter the types of container

- [x] setup redux store
- [x] and the states
- [x] make it
- [x] filter the geojson
- [x] show just the filtered points
- [x] unify style of the geojson to have it all together
- [x] have some categories for the different types
- [x] batch show and hide for the categories then

**Comment by LukasBaecker** [comment]
- [ ] setup redux store
- [ ] and the states
- [ ] make it
- [ ] filter the geojson
- [ ] show just the filtered points

**Comment by jonathom** [comment]
I think this should be a menu from which people can choose their purpose instead of the overwhelming amount if different recycling_types. See #7
